# npm install, npm run translations:write npm run translations:upload
name: "Upload Crowdin Sources"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Write translations
        run: yarn translations:write

      - name: Upload translations
        run: yarn translations:upload
